### ISSUE TITLE
F3 version cutoff

### ISSUE THREAD

**Issue by Aqarius90** [folkarps/FAMDB#21]
Implement an F3 version selector, either as a lower cutoff, to avoid error messages, or as from-to, to facilitate mission updates.

**Comment by SamLex** [comment]
My thoughts on this would be to have a dropdown (like the Status dropdown) with 4 options:
- `All Framework versions`
- `Ancient F3 (<= 3.3.x)` - show only missions with "F3 3.3.x or older"
- `Legacy F3 (3.4.x)` - show only missions with "F3 3.4.0" or "F3 3.4.1"
- `Modern FA3 (>= 3.5.x)` - show only missions with 3.5.0 or above

I think this fits into the category of "lower cutoff". I like the idea of grouping the versions under a textual description for ease-of-use for a user that doesn't know which F3 version is which. I'm flexible on the actual textual descriptions and cutoffs, above is just an example (e.g. we potentially might want to consider the first few 3.5.x under "legacy", not 100% how they've "aged").

**Comment by SamLex** [comment]
@Aqarius90 @NikkoJT Any thoughts or objections on categorising frameworks like above, and searching on categories? The exact categories and threshold are flexible and will be easy to adjust / add new categories in future

**Comment by NikkoJT** [comment]
No objections from me.

**Comment by Aqarius90** [comment]
Looks fine

**Comment by SamLex** [comment]
Merged and live :smile:
