### ISSUE TITLE
Missions with no files can't be marked as broken because you can't comment

### ISSUE THREAD

**Issue by SamLex** [folkarps/FAMDB#6]
Split from #1

**Comment by SamLex** [comment]
@NikkoJT there isn't really a reason we'd want a mission with no files _not_ marked as broken, right? Reason is I'm thinking of making this part of either Cleanup or Sync (probably Cleanup). E.g. if a mission has no files -> set status to broken. Seems a bit neater than having to manually do it if this situation occurs.

**Comment by NikkoJT** [comment]
Yes, that seems fair.

**Comment by SamLex** [comment]
@NikkoJT This is now implemented and on live. This will take effect the next time CleanUp is run from the admin page.
