### ISSUE TITLE
Add a searchable tag system, and possibly make descriptions searchable

### ISSUE THREAD

**Issue by SamLex** [folkarps/FAMDB#9]
Split from #1

**Comment by SamLex** [comment]
> possibly make descriptions searchable

@NikkoJT My current thought is to make this the users choice without adding more buttons to the UI.

![search-text-tooltip](https://user-images.githubusercontent.com/733683/184493750-0b2cade4-45ce-47e8-a0f5-ad44d9e33704.png)

`@desc` and `@notes` would be special keywords in the search textbox to make the search apply to the mission description and/or the mission notes, in addition to the mission name.

For example:
* `nato` - search for nato (case insensitive) in the mission name
* `nato @desc` - search for nato (case insensitive) in the mission name **or** mission description
* `nato @notes` - search for nato (case insensitive) in the mission name **or** mission notes
* `nato @desc @notes` - search for nato (case insensitive) in the mission name, mission description, **or** mission notes

**Comment by NikkoJT** [comment]
That seems reasonable, although I would also be in favour of a checkbox to toggle description/notes searching. I understand if you want to avoid adding more of those though.

**Comment by SamLex** [comment]
Yeah, I'll see what I can do. I'm mainly concerned about how big the filters panel is and don't really want to make it bigger (technical side is no issue). I might see if I can tweak some of the others to reduce the size (e.g. make "type" a multi-select dropdown instead of checkboxes)

**Comment by NikkoJT** [comment]
Could a checkbox go inline with the "Search" string above the input field? I reckon a "Search desc." and "Search notes" would fit in there at the same font size.

**Comment by SamLex** [comment]
Yes is the answer to inline.

For the fun of it, thought I'd try rearranging the search panel to be much more compact. Just experimenting really. Thoughts?
![search-compact](https://user-images.githubusercontent.com/733683/184510536-ba1806b6-9cb0-4065-b503-6237ab727871.png)

**Comment by NikkoJT** [comment]
That looks really great. I think Reset and Apply should keep black text, it's more readable and matches all the other buttons, but the layout is good. 
At risk of [upsetting some people](https://xkcd.com/1172/) I'd say we could even save a little more space by dropping the playcount filter. I don't think it really offers anything useful that can't also be had by just sorting by playcount in the main list.

~~left align slots and playcount, you monster~~

**Comment by SamLex** [comment]
Awesome, I'll work with this layout as a base then. The white buttons and other colour changes were unintentional (I have a "dark mode" browser extension I didn't notice was on here that flipped the colour, think it did a few other things as well), so I'll keep those black.

Agree on the playcount filter, it doesn't add much and will buy some space for the "tags" filter to come.

And yes, the alignment is a mess, this was just the existing alignment copy/pasted with some small tweaks to the vertical spacing as a mock-up. I'll fight with the CSS to make it align properly now.

**Comment by NikkoJT** [comment]
For tags, I think we should use a set of predefined tags so that they can be trusted to contain useful information, and not to depend on whether the missionmaker chose to tag "mech", "mechanised", or "mechanized".

When the idea first got raised I collected this list as a starting point.
[famdb tags.txt](https://github.com/folkarps/FAMDB/files/9333816/famdb.tags.txt)

**Comment by SamLex** [comment]
I was originally going to do free-form tags, but a predefined set also works for me. And does avoid the "multiple variants of the same thing" issue. The list will probably be defined in code, at least initially. Might add an admin UI for it in the future.

QQ - for the tags that are two words (e.g. 'noreinforcements'), do you think
1. no separator ('noreinforcements')
2. underscore ('no_reinforcements')
3. or space ('no reinforcements')
Is better?

Might also style them in uppercase ('NOREINFORCEMENTS') for consistency with a few other places.

**Comment by NikkoJT** [comment]
Underscore is my favourite style for tags and I think it has the least ambiguity.

I'm inclined towards all lowercase tbh, it matches our other technical styles (e.g. in F3, in mission PBO names) and is easier on the eyes. But, I'm not gonna start a fight over it.

**Comment by SamLex** [comment]
Second draft of new search panel. Main changes:
- Fix colour issues caused by extension
- Removed Playcount
- Swapped order of Type and Slots
- Changed Type and Slots to mimic style of Search. IMO breaks up the panel at bit better
- Lots of faffying with alignment, width, and spacing.


![famdb-search-draft2](https://user-images.githubusercontent.com/733683/189497679-f9aec641-3d06-463f-a083-99b994e50b98.png)


@NikkoJT Thoughts? Hopefully have alignment and spacing right, lmk if something is off.

**Comment by NikkoJT** [comment]
That all looks good to me!

**Comment by SamLex** [comment]
I've pushed those changes to live, no point them waiting until I've done the tag system.
